### ISSUE TITLE
Any information on how to implement this. 

### ISSUE THREAD

**Issue by chibill** [ProtoDef-io/ProtoDef#19]

**Comment by chibill** [comment]
The only information at I have to implement this is the data types doc that does not really define much.
Any other information that could help someone trying to implement this. (Considering there are only two implementations that are public and on github.)

**Comment by hansihe** [comment]
What more information do you want to know? The spec is fairly comprehensive, and if there is anything that needs disambiguation you could either open an issue about it so that it can be added to the spec, or look at the protocol files in the minecraft-data repo for examples.

If there is anything specific you want to know, I would be more than happy to help out as much as I can. It is a bit difficult to help when there is only a generic question.

If you prefer a more casual forum of discussion, you could join us in the gitter.im channel.

**Comment by chibill** [comment]
I am here because I want to make something to use the protocol file from Minecraft-data. But there is not much information on how to use the data types. And the protocol.md says basically nothing

**Comment by chibill** [comment]
Also if there was enough information there would be more then two impl. (And by people other then the ones working on the project.)

**Comment by roblabla** [comment]
Hansihe made an impl before he was a member of protodef.

I'm closing this issue. If you have a specific problem, feel free to reopen with more information, we'll be glad to help.
