### ISSUE TITLE
Add half-precision floating-point type

### ISSUE THREAD

**Issue by Saiv46** [ProtoDef-io/ProtoDef#32]
See https://en.wikipedia.org/wiki/Half-precision_floating-point_format

**Comment by rom1504** [comment]
We could be why ? Any protocol using that ?

**Comment by Saiv46** [comment]
It used by python `struct` module, I can convert it to ProtoDef

**Comment by rom1504** [comment]
Yes I'm not saying it's hard to implement, it's definitely not hard.
My question is why would we support it ? Is there any protocol you have in mind that uses this ?

**Comment by roblabla** [comment]
As a general rule, the vision I have for protodef is to have a very lean/minimal core that is mostly focused on generic containers and universal datatypes to enable 90% of the use-cases (in that sense, varint support in protodef was a mistake). More niche datatypes can exist as pluggable extensions, like how NMP adds UUID. This reduces maintenance of the core library and more easily allows experimentation (e.g. with compilers and such) since they don't initially have to worry about every weird datatype.

`f16` feels extremely niche - I've never seen it used outside deep learning frameworks. Most languages don't natively support it (e.g. nodejs doesn't have a function on Buffer to read a half-float, Rust doesn't natively support f16, etc...), which would mean we'd have to roll our own. IMO this likely means that it'd be better suited as an out-of-tree extension.

**Comment by Saiv46** [comment]
Maybe we should have additional datatypes as one extension package?

And name it like `protodef-extensions` to standartalize additional datatypes and `node-protodef-extensions` for implementation

**Comment by rom1504** [comment]
Why not but I think it would be good to have a name more specific than this
so it doesn't end up being a pile of hundred of random types.

What else but float16 would go in that ?

**Comment by rom1504** [comment]
What I've been doing is putting specific types where they are needed (eg in
prismarine-nbt, in node-minecraft-protocol, in pocket-minecraft-protocol,
in node-diablo-protocol) and it works pretty well since protodef is
extendable.
There has been only a few rare case (one was adding little endians
numerical types for pocket-minecraft-protocol) where the types where
generic enough and common enough that we thought it was useful to add them
in protodef itself.

Maybe that approach would work for your use case too ?
